# Generated by Django 4.2.9 on 2025-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience (integer).', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma separated list or free-form skills text.'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
