# Generated by Django 4.2.9 on 2025-10-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_member_experience_member_skills_member_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='developer_type',
            field=models.CharField(blank=True, choices=[('web', 'Web Developer'), ('mobile', 'Mobile Developer'), ('uiux', 'UI/UX Designer'), ('other', 'Other')], help_text='Type of developer: web, mobile, or UI/UX designer.', max_length=10, null=True),
        ),
    ]
