# Generated by Django 4.2.9 on 2025-10-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_invitation_accepted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_by',
        ),
    ]
