# Generated by Django 4.2.9 on 2025-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(help_text='What happened (e.g. "requested extra time")', max_length=255),
        ),
    ]
