# Generated by Django 4.2.9 on 2025-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time_request',
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(max_length=255),
        ),
    ]
