# Generated by Django 4.2.9 on 2025-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timerequest_delete_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerequest',
            name='requested_duration',
            field=models.DurationField(editable=False),
        ),
    ]
