# Generated by Django 4.2.9 on 2025-10-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_remove_notification_time_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='timesheet.timerequest'),
        ),
    ]
