'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Layout/Header";
import Sidebar from "@/components/Layout/Sidebar";
 // Bootstrap CSS
import BootstrapClient from "@/components/BootstrapClient"; // Import the client component
import Script from 'next/script'
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'react-datepicker/dist/react-datepicker.css';

import Head from 'next/head';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "WEBWIZ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>


) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden g-scroll`}
      >
         <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
         <BootstrapClient />
        {/* Header Component */}
         <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="lazyOnload"
        />

        

        {/* Main Layout with Sidebar and Children */}
          {/* Main Content Area */}
          <main id="main"  className="">
            <div className="container-fluid">
              <div className="row main-inner-row">
                <div className="col-lg-2 px-lg-0 sidebar-col">
                  {/* build change  */}
                  {/* <Sidebar /> */}
                  <Sidebar collapsed={false} toggleSidebar={() => {}} />

                </div>
                <div className="col-lg-10 px-lg-0 content-col px-0">
                  
                  <Header />
                  <div className="content-main px-3 g-scroll">
                  {children}
                  </div>
                </div>
              </div>
            </div>
           
          </main>
     
      </body>
    </html>
  );
}