# Generated by Django 4.2.9 on 2025-09-29 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_type', models.CharField(blank=True, choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Both', 'Both')], max_length=10, null=True)),
                ('web_desc', models.TextField(blank=True, null=True)),
                ('mobile_desc', models.TextField(blank=True, null=True)),
                ('figma_desc', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskai_tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Task AI',
                'verbose_name_plural': 'Tasks AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
