# Generated by Django 4.2.9 on 2025-10-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_api', '0002_add_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='ai_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskai',
            name='ai_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskai',
            name='ai_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskai',
            name='ai_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskai',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskai',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_taskai_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskai',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_taskai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskai',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taskai', to=settings.AUTH_USER_MODEL),
        ),
    ]
