# Generated by Django 4.2.9 on 2025-10-20 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_taskai_ai_confidence_taskai_ai_meta_taskai_ai_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='assignment_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='When True the task should not be reassigned by non-staff (set by AI auto-assign).'),
        ),
        migrations.AlterField(
            model_name='taskai',
            name='ai_confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Confidence from AI selection (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
