# Generated by Django 5.2.7 on 2025-12-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_invitation_accepted_by'),
        ('shifts', '0002_alter_shift_required_hours_alter_shift_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_notifications', to='projects.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
