# Generated by Django 5.2.7 on 2025-12-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_invitation_accepted_by'),
        ('shifts', '0003_shiftnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date for the attendance (shift local date)')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_TIME', 'On time'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ON_TIME', max_length=16)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('tracked_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.member')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='shifts.shift')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('member', 'shift', 'date')},
            },
        ),
    ]
