# Generated by Django 5.2.7 on 2025-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'On time'), ('LATE', 'Late'), ('ABSENT', 'Absent')], max_length=16, null=True),
        ),
    ]
